#ifndef WORDS_H
#define WORDS_H

#define THREE_LTR_WORDS 1
#define FOUR_LTR_WORDS 38
#define FIVE_LTR_WORDS 79
#define SIX_LTR_WORDS 111
#define SEVEN_LTR_WORDS 135
#define EIGHT_LTR_WORDS 161
#define LONG_WORDS 177
#define TOTAL_CHAR_COUNT 70

#endif // WORDS_H
